In [2]:
import pandas as pd
import numpy as np

In [5]:
customers_raw= pd.read_csv(r"C:\Anas Jamal\Credit Collections Prioritization Engine\customers_raw.csv")

In [7]:
loans_raw= pd.read_csv(r"C:\Anas Jamal\Credit Collections Prioritization Engine\loans_raw.csv")

In [9]:
collectors_raw = pd.read_csv(r"C:\Anas Jamal\Credit Collections Prioritization Engine\collectors_raw.csv")

In [11]:
collections_status_raw = pd.read_csv(r"C:\Anas Jamal\Credit Collections Prioritization Engine\collections_status_raw.csv")

In [12]:
print(customers_raw.info())
print(loans_raw.info())
print(collectors_raw.info())
print(collections_status_raw.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10025 entries, 0 to 10024
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       10025 non-null  object
 1   City              10025 non-null  object
 2   Region            10025 non-null  object
 3   Income_Band       9975 non-null   object
 4   Credit_Score      9985 non-null   float64
 5   Customer_Segment  10025 non-null  object
dtypes: float64(1), object(5)
memory usage: 470.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10025 entries, 0 to 10024
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Loan_ID        10025 non-null  object
 1   Customer_ID    10025 non-null  object
 2   Loan_Type      10025 non-null  object
 3   Loan_Amount    10025 non-null  int64
 4   EMI_Amount     10005 non-null  float64
 5   Start_Date     10025 non-null  object
 6   Tenure_Months  10025 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 548.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Agent_ID          75 non-null     object
 1   City              75 non-null     object
 2   Experience_Level  72 non-null     object
 3   Team              75 non-null     object
dtypes: object(4)
memory usage: 2.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10025 entries, 0 to 10024
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loan_ID             10025 non-null  object
 1   Agent_ID            10025 non-null  object
 2   Report_Month        10025 non-null  object
 3   Outstanding_Amount  10025 non-null  float64
 4   Days_Past_Due       10025 non-null  int64
 5   Missed_EMIs         10025 non-null  int64
 6   Contact_Response    10025 non-null  object
 7   Recovery_Status     10025 non-null  object
 8   Amount_Recovered    10010 non-null  float64
dtypes: float64(2), int64(2), object(5)
memory usage: 705.0+ KB
None

In [27]:
print(customers_raw.shape)
print(loans_raw.shape)
print(collectors_raw.shape)
print(collections_status_raw.shape)

(10025, 6)
(10025, 7)
(75, 4)
(10025, 9)

In [29]:
customers_raw.head()

  Customer_ID    City Region Income_Band  Credit_Score Customer_Segment
0   CUST10000  mumbai   East      Medium         674.0             Mass
1   CUST10001  mumbai  South      Medium         682.0         Affluent
2   CUST10002  mumbai   East      Medium         655.0             Mass
3   CUST10003  mumbai  South        High         789.0         Affluent
4   CUST10004  mumbai   West      Medium         677.0             Mass

In [36]:
collections_status_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10025 entries, 0 to 10024
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loan_ID             10025 non-null  object
 1   Agent_ID            10025 non-null  object
 2   Report_Month        10025 non-null  object
 3   Outstanding_Amount  10025 non-null  float64
 4   Days_Past_Due       10025 non-null  int64
 5   Missed_EMIs         10025 non-null  int64
 6   Contact_Response    10025 non-null  object
 7   Recovery_Status     10025 non-null  object
 8   Amount_Recovered    10010 non-null  float64
dtypes: float64(2), int64(2), object(5)
memory usage: 705.0+ KB

In [52]:
collections_status_raw.duplicated().sum()

np.int64(0)

In [1]:
collectors_raw.info()

NameError: name 'collectors_raw' is not defined

In [54]:
customers_raw.head()

  Customer_ID    City Region Income_Band  Credit_Score Customer_Segment
0   CUST10000  mumbai   East      Medium         674.0             Mass
1   CUST10001  mumbai  South      Medium         682.0         Affluent
2   CUST10002  mumbai   East      Medium         655.0             Mass
3   CUST10003  mumbai  South        High         789.0         Affluent
4   CUST10004  mumbai   West      Medium         677.0             Mass

In [66]:
collections_status_raw["Contact_Response"].value_counts()

Contact_Response
Responsive        3391
Promise to Pay    3315
No Answer         3298
no answer           21
Name: count, dtype: int64

In [69]:
customers_raw.head()

  Customer_ID    City Region Income_Band  Credit_Score Customer_Segment
0   CUST10000  mumbai   East      Medium         674.0             Mass
1   CUST10001  mumbai  South      Medium         682.0         Affluent
2   CUST10002  mumbai   East      Medium         655.0             Mass
3   CUST10003  mumbai  South        High         789.0         Affluent
4   CUST10004  mumbai   West      Medium         677.0             Mass

In [71]:
customers_clean=customers_raw.copy()

In [73]:
customers_clean.head()

  Customer_ID    City Region Income_Band  Credit_Score Customer_Segment
0   CUST10000  mumbai   East      Medium         674.0             Mass
1   CUST10001  mumbai  South      Medium         682.0         Affluent
2   CUST10002  mumbai   East      Medium         655.0             Mass
3   CUST10003  mumbai  South        High         789.0         Affluent
4   CUST10004  mumbai   West      Medium         677.0             Mass

In [87]:
customers_clean['City'].value_counts()

City
Delhi NCR    1709
Mumbai       1707
Pune         1668
Hyderabad    1667
Kolkata      1666
Bangalore    1608
Name: count, dtype: int64

In [83]:
customers_clean['City']=customers_clean['City'].str.strip().str.title()

In [88]:
customers_clean['City']=customers_clean['City'].replace({"Delhi Ncr":"Delhi NCR"})

In [106]:
customers_clean["Income_Band"]=customers_clean["Income_Band"].fillna('Medium')

In [112]:
customers_clean.isnull().sum()

Customer_ID         0
City                0
Region              0
Income_Band         0
Credit_Score        0
Customer_Segment    0
dtype: int64

In [113]:
customers_clean['Credit_Score'] = customers_clean['Credit_Score'].fillna(
    customers_clean['Credit_Score'].median()
)

In [116]:
customers_clean=customers_clean.drop_duplicates()

In [123]:
customers_clean.duplicated().sum()

np.int64(0)

In [122]:
customers_clean['Credit_Score']=customers_clean['Credit_Score'].fillna(customers_clean['Credit_Score'].median())

In [124]:
customers_clean.shape

(10000, 6)

In [15]:
customers_clean.to_csv('customers_clean.csv', index=False)

NameError: name 'customers_clean' is not defined

In [20]:
loans_clean= loans_raw.copy()

In [21]:
loans_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10025 entries, 0 to 10024
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Loan_ID        10025 non-null  object
 1   Customer_ID    10025 non-null  object
 2   Loan_Type      10025 non-null  object
 3   Loan_Amount    10025 non-null  int64
 4   EMI_Amount     10005 non-null  float64
 5   Start_Date     10025 non-null  object
 6   Tenure_Months  10025 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 548.4+ KB

In [28]:
loans_clean.head(5)

,Loan_ID,Customer_ID,Loan_Type,Loan_Amount,EMI_Amount,Start_Date,Tenure_Months
0,LN20000,CUST10000,credit card,300430,25035.83,2023-04-10,12
1,LN20001,CUST10001,credit card,27237,2269.75,2023-04-14,12
2,LN20002,CUST10002,credit card,230581,19215.08,2024-06-10,12
3,LN20003,CUST10003,credit card,23901,1991.75,2024-01-24,12
4,LN20004,CUST10004,credit card,220493,18374.42,2024-10-09,12

In [31]:
loans_clean['Loan_Type'].value_counts()

Loan_Type
Credit Card         3394
Personal Loan       3352
Consumer Durable    3258
credit card           21
Name: count, dtype: int64

In [35]:
loans_clean['Loan_Type']=loans_clean['Loan_Type'].str.strip().str.title()

In [36]:
loans_clean['Loan_Type'].value_counts()

Loan_Type
Credit Card         3415
Personal Loan       3352
Consumer Durable    3258
Name: count, dtype: int64

In [42]:
loans_clean['EMI_Amount'].isnull().sum()

np.int64(20)

In [41]:
loans_clean.groupby('Loan_Type')['EMI_Amount']

In [48]:
loans_clean['Loan_Type'].isnull().sum()

np.int64(0)

In [49]:
loans_clean['EMI_Amount']=loans_clean.groupby('Loan_Type')['EMI_Amount'].transform(lambda x:x.fillna(x.median()))

In [54]:
loans_clean['Loan_Type'].isnull().sum()

np.int64(0)

In [53]:
loans_clean.shape

(10025, 7)

In [52]:
loans_clean.to_csv('loans_clean.csv', index=False)

In [55]:
collectors_raw.head(5)

  Agent_ID    City Experience_Level         Team
0   AGT100  mumbai           Senior  Retail Team
1   AGT101  mumbai              Mid   Field Team
2   AGT102  mumbai              Mid  Retail Team
3   AGT103  mumbai              Mid  Retail Team
4   AGT104  mumbai           Senior  Retail Team